name: Dev - Run tests and pulumi preview

on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    container: public.ecr.aws/o3o6u9e4/pulumi.python.gcc:latest
    environment: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PULUMI_ACCESS_TOKEN:  ${{ secrets.PULUMI_ACCESS_TOKEN }}
      MONGO_URL:  ${{ secrets.MONGO_URL }}
      ENV:  ${{ secrets.ENV }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      # TODO: set up cache
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install pip and dependencies
        shell: bash
        run: |
          python3.10 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements_dev.txt

      # GHA run in a different context and git commands will fail. 
      # As our pulumi files use git commands, set the directories to safe to work around
      # the git file security
      - name: Mark folders safe for git
        shell: bash
        run: |
          git config --global --add safe.directory '*'
     
      - name: run tests
        shell: bash
        run: |
          venv/bin/python -m pytest trading_api
      
      - name: run deploy preview
        shell: bash
        run: |
          venv/bin/python -m deploy preview -e $ENV
