name: Dev - Run tests 

on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    container: public.ecr.aws/o3o6u9e4/pulumi.python.gcc:latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      # TODO: set up cache
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install pip and dependencies
        shell: bash
        run: |
          python3.10 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements_dev.txt

      - name: run tests
        shell: bash
        run: |
          venv/bin/python -m pytest jsonlog
      
